### ISSUE TITLE
Move into /post

### ISSUE THREAD

**Issue by bep** [larsth/www.larsth.dk#1]
If you move the content into the section /post, it should work without panic with Hyde-x.

You should of course be able to have any section you want, but the hyde-x theme has a hardcoded filter for that section.

It crashes because the paginator didn't handle 0 pages. It does now.

**Comment by larsth** [comment]
Thank you for your comment.

It fixed the problem.

**Comment by larsth** [comment]
Note to self, while it is still in fresh memory:
`bep` wrote this comment, because he is one the maintainers of spf/hugo, and I posted a bug report:
https://github.com/spf13/hugo/issues/1112
